[package]
name = "lin_bevy_jam"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.8"
leafwing-input-manager = "0.5.0"
bevy-simple-state-machine = "0.1.0"

# Optimize dependencies
[profile.dev.package."*"]
opt-level = 3
